version: "3.9"

services:
  app:
    build:
      context: .
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    volumes:
       - ../TSF-bin:/TSF-bin