version: "3.9"

services:
  app_training:
    build:
      context: ./app_training
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    volumes:
       - ../tsf-bin:/tsf-bin