version: "3.9"

services:
  app_training:
    build:
      context: ./app_training
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    volumes:
       - ../tsf-bin:/tsf-bin
  # app_tensorboard:
  #   build:
  #     context: ./app_tensorboard
  #   volumes:
  #      - ../tsf-bin:/tsf-bin
  #   ports:
  #     - "6006:6006"
  #   stdin_open: true
  #   tty: true