version: "3.9"

services:
  app:
    build:
      context: .
    deploy:
      resources:
        reservations:
          devices:
          - driver: "nvidia"
            device_ids: ["0"]
            capabilities: [gpu]
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ../TSF-bin:/TSF-bin