version: "3.9"

services:
  app_jupyter:
    build:
      context: .
    volumes:
      - ../../tsf-bin:/tf/tsf-bin
    ports:
      - "8888:8888"
      - "6006:6006"
    stdin_open: true
    tty: true