ARTIFACTS_FOLDER = r'C:\Users\yunus\Desktop\Artifacts'

BATCH_SIZE = 500
MINI_BATCH_SIZE = 32
NR_OF_EPOCHS = 3

TEST_SIZE = 500

DISERT_NPP_LR = 1e-2
DISERT_MPP_LR = 1e-2
DISERT_SPP_LR = 1e-2
DISERT_RPP_LR = 1e-2


TICERT_NPP_LR = 1e-2
TICERT_MPP_LR = 1e-2
TICERT_SPP_LR = 1e-2
TICERT_RPP_LR = 1e-2


TREERT_NPP_LR = 1e-2
TREERT_MPP_LR = 1e-2
TREERT_SPP_LR = 1e-2
TREERT_RPP_LR = 1e-2


SEAERT_NPP_LR = 1e-2
SEAERT_MPP_LR = 1e-2
SEAERT_SPP_LR = 1e-2
SEAERT_RPP_LR = 1e-2