#!/bin/bash

cd ../app_raw_data_formatter/

docker-compose run --rm app_data_formatter \
    02_build_datasets.py \
    --channel=EURUSD \
    --target_group=ticker \
    --forecast_horizon=120 \
    --lookback_coefficient=4 \
    --step_size=30 \
    --test_size=500

docker-compose run --rm app_data_formatter \
    03_convert_time_indices_to_date_features.py \
    --channel=EURUSD \
    --raw_frequency=m \
    --datetime_features="['month', 'day', 'dayofweek', 'hour', 'minute']"

docker-compose run --rm app_data_formatter \
    02_build_datasets.py \
    --channel=GBPUSD \
    --target_group=ticker \
    --forecast_horizon=120 \
    --lookback_coefficient=4 \
    --step_size=30 \
    --test_size=500

docker-compose run --rm app_data_formatter \
    03_convert_time_indices_to_date_features.py \
    --channel=GBPUSD \
    --raw_frequency=m \
    --datetime_features="['month', 'day', 'dayofweek', 'hour', 'minute']"

docker-compose run --rm app_data_formatter \
    02_build_datasets.py \
    --channel=USDCAD \
    --target_group=ticker \
    --forecast_horizon=120 \
    --lookback_coefficient=4 \
    --step_size=30 \
    --test_size=500

docker-compose run --rm app_data_formatter \
    03_convert_time_indices_to_date_features.py \
    --channel=USDCAD \
    --raw_frequency=m \
    --datetime_features="['month', 'day', 'dayofweek', 'hour', 'minute']"