#!/bin/bash

cd ../app_raw_data_formatter/

docker-compose down

docker-compose build

docker-compose run --rm app_data_formatter \
    02_build_datasets.py \
    --channel=EURUSD \
    --target_group=ticker \
    --forecast_horizon=120 \
    --lookback_coefficient=4 \
    --step_size=30 \
    --test_size=500

docker-compose run --rm app_data_formatter \
    02_build_datasets.py \
    --channel=GBPUSD \
    --target_group=ticker \
    --forecast_horizon=120 \
    --lookback_coefficient=4 \
    --step_size=30 \
    --test_size=500

docker-compose run --rm app_data_formatter \
    02_build_datasets.py \
    --channel=USDCAD \
    --target_group=ticker \
    --forecast_horizon=120 \
    --lookback_coefficient=4 \
    --step_size=30 \
    --test_size=500
