services:
  input_pipeline_dev:
    build:
      context: .
    volumes:
       - ../../../tsf-bin:/workspace/tsf-bin
       - ../task:/workspace:cached
    command: /bin/sh -c "sleep infinity"
    env_file:
      - ../../dir_names.env
